#!/bin/bash

# query pager from the config file
pager=$(buc "toobig_pager")

if [ -z "$pager" ]; then
	echo "toobig_pager must be set in $CONFIG_FILE."
	exit 1
fi

# ensure file argument is provided
if [ $# -ne 1 ]; then
	echo "usage: $0 <file>"
	exit 1
fi

FILE="$1"

# ensure file exists
if [ ! -f "$FILE" ]; then
	echo "file not found: $FILE"
	exit 1
fi

# cat the file someway
FILE="$1"
terminal_height=$(tput lines)
file_lines=$(wc -l < "$FILE")

cat "$FILE"

if [ "$file_lines" -ge "$terminal_height" ]; then
	cat "$FILE" | less
fi
