#!/bin/bash

# Query pager from the config file
pager=$(buc "toobig_pager")

if [ -z "$pager" ]; then
    echo "toobig_pager must be set in $CONFIG_FILE."
    exit 1
fi

# If no file is provided, read from stdin
if [ $# -eq 0 ]; then
    input_source="/dev/stdin"
else
    FILE="$1"
    # Ensure the file exists if provided
    if [ ! -f "$FILE" ]; then
        echo "file not found: $FILE"
        exit 1
    fi
    input_source="$FILE"
fi

# Get terminal height
terminal_height=$(tput lines)

# Count the number of lines in the input
file_lines=$(cat "$input_source" | tee /dev/tty | wc -l)

# Use pager if the input exceeds the terminal height
if [ "$file_lines" -ge "$terminal_height" ]; then
    cat "$input_source" | less
else
    cat "$input_source"
fi
